#!/bin/bash

SUBJ=$1
OUTDIR=$2
SURF=smoothwm

# ## example test view - coronal front
# freeview -f $SUBJECTS_DIR/$1/surf/lh.${SURF}:edgethickness=0:annot=aparc.DKTatlas40.annot \
#          -f $SUBJECTS_DIR/$1/surf/rh.${SURF}:edgethickness=0:annot=aparc.DKTatlas40.annot \
#          --viewport '3d' --viewsize 900 900 -cam zoom 1.5 azimuth -90 

##
## SUBJECT_DIR needs to be defined
##

## sagittal left
freeview -f $SUBJECTS_DIR/$1/surf/lh.${SURF}:edgethickness=0:annot=aparc.DKTatlas40.annot \
         --viewport '3d' --viewsize 900 900 -cam zoom 1.5 -ss $OUTDIR/${SUBJ}_${SURF}_sagittal_left

## sagittal right
freeview -f $SUBJECTS_DIR/$1/surf/rh.${SURF}:edgethickness=0:annot=aparc.DKTatlas40.annot \
         --viewport '3d' --viewsize 900 900 -cam azimuth 180 zoom 1.5 -ss $OUTDIR/${SUBJ}_${SURF}_sagittal_right

## medial left
freeview -f $SUBJECTS_DIR/$1/surf/lh.${SURF}:edgethickness=0:annot=aparc.DKTatlas40.annot \
         --viewport '3d' --viewsize 900 900 -cam azimuth 180 zoom 1.5 -ss $OUTDIR/${SUBJ}_${SURF}_medial_left

## medial right
freeview -f $SUBJECTS_DIR/$1/surf/rh.${SURF}:edgethickness=0:annot=aparc.DKTatlas40.annot \
         --viewport '3d' --viewsize 900 900 -cam zoom 1.5 -ss $OUTDIR/${SUBJ}_${SURF}_medial_right

## coronal front
freeview -f $SUBJECTS_DIR/$1/surf/lh.${SURF}:edgethickness=0:annot=aparc.DKTatlas40.annot \
         -f $SUBJECTS_DIR/$1/surf/rh.${SURF}:edgethickness=0:annot=aparc.DKTatlas40.annot \
         --viewport '3d' --viewsize 900 900 -cam azimuth -90 zoom 1.5 -ss $OUTDIR/${SUBJ}_${SURF}_coronal_front

## coronal back
freeview -f $SUBJECTS_DIR/$1/surf/lh.${SURF}:edgethickness=0:annot=aparc.DKTatlas40.annot \
         -f $SUBJECTS_DIR/$1/surf/rh.${SURF}:edgethickness=0:annot=aparc.DKTatlas40.annot \
         --viewport '3d' --viewsize 900 900 -cam azimuth 90 zoom 1.5 -ss $OUTDIR/${SUBJ}_${SURF}_coronal_back

## axial top
freeview -f $SUBJECTS_DIR/$1/surf/lh.${SURF}:edgethickness=0:annot=aparc.DKTatlas40.annot \
         -f $SUBJECTS_DIR/$1/surf/rh.${SURF}:edgethickness=0:annot=aparc.DKTatlas40.annot \
	 --viewport '3d' --viewsize 900 900 -cam elevation 90 zoom 1.5 -ss $OUTDIR/${SUBJ}_${SURF}_axial_top

## axial bottom
freeview -f $SUBJECTS_DIR/$1/surf/lh.${SURF}:edgethickness=0:annot=aparc.DKTatlas40.annot \
         -f $SUBJECTS_DIR/$1/surf/rh.${SURF}:edgethickness=0:annot=aparc.DKTatlas40.annot \
         --viewport '3d' --viewsize 900 900 -cam elevation -90 zoom 1.5 -ss $OUTDIR/${SUBJ}_${SURF}_axial_bottom
